image: node:22-bookworm

variables:
  EXPO_NO_TELEMETRY: '1'
  HUSKY: '0'

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

stages:
  - validate
  - bundle

default:
  before_script:
    - corepack enable
    - pnpm install --frozen-lockfile --store-dir .pnpm-store

validate:
  stage: validate
  script:
    - pnpm validate

bundle:
  stage: bundle
  script:
    - pnpm build
